//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertMessage
    {
        public long Id { get; set; }
        public Nullable<long> CreatorId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
