//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> RoleId { get; set; }
        public Nullable<System.DateTime> BanDateTime { get; set; }
        public Nullable<System.DateTime> UnbanDateTime { get; set; }
        public string BanReason { get; set; }
        public string UnbanReason { get; set; }
        public Nullable<bool> CanBeUnbanned { get; set; }
        public Nullable<long> AdminBanId { get; set; }
        public Nullable<long> AdminUnbanId { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
