//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeolocationPlatformPercentage
    {
        public long Id { get; set; }
        public Nullable<long> GeolocationId { get; set; }
        public Nullable<long> Percentage { get; set; }
        public long PerformerPlatformId { get; set; }
    
        public virtual Geolocation Geolocation { get; set; }
        public virtual PerformerPlatform PerformerPlatform { get; set; }
    }
}
