//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.OrderContent = new HashSet<OrderContent>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageData { get; set; }
        public long ImageSize { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> ImageWidth { get; set; }
        public Nullable<int> ImageHeight { get; set; }
        public string Extension { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<OrderContent> OrderContent { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
