//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyTransfers
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Action { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> MerchantId { get; set; }
        public string AccountMerchantSystem { get; set; }
        public string TransactionId { get; set; }
        public string Status { get; set; }
        public string StatusDescription { get; set; }
    
        public virtual Merchants Merchants { get; set; }
        public virtual User User { get; set; }
    }
}
