//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderContent
    {
        public OrderContent()
        {
            this.OrderPerformed = new HashSet<OrderPerformed>();
        }
    
        public long Id { get; set; }
        public long IdOrder { get; set; }
        public long IdContent { get; set; }
        public string Status { get; set; }
        public string ContentType { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Order Order { get; set; }
        public virtual Video Video { get; set; }
        public virtual ICollection<OrderPerformed> OrderPerformed { get; set; }
    }
}
