//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformerPlatform
    {
        public PerformerPlatform()
        {
            this.GeolocationPlatformPercentage = new HashSet<GeolocationPlatformPercentage>();
            this.OrderPerformed = new HashSet<OrderPerformed>();
            this.PerformerStatistics = new HashSet<PerformerStatistics>();
        }
    
        public long Id { get; set; }
        public Nullable<long> PerformerId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public Nullable<long> ThemeId { get; set; }
        public string Verified { get; set; }
        public Nullable<System.DateTime> LastOnlineDateTime { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<GeolocationPlatformPercentage> GeolocationPlatformPercentage { get; set; }
        public virtual ICollection<OrderPerformed> OrderPerformed { get; set; }
        public virtual Themes Themes { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PerformerStatistics> PerformerStatistics { get; set; }
    }
}
