//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformerStatistics
    {
        public long Id { get; set; }
        public Nullable<long> PerformerPlatformId { get; set; }
        public Nullable<long> AverageViewerCountPerHour { get; set; }
        public Nullable<long> MaxViewersCount { get; set; }
        public Nullable<long> TotalUniqueViews { get; set; }
        public Nullable<long> TotalFollowers { get; set; }
        public Nullable<decimal> TotalViews { get; set; }
        public Nullable<long> Likes { get; set; }
        public Nullable<long> CompletedOrders { get; set; }
        public Nullable<long> TotalOrders { get; set; }
        public Nullable<decimal> AverageComplitionSpeed { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Status { get; set; }
        public Nullable<long> UniqueViewersForMonth { get; set; }
    
        public virtual PerformerPlatform PerformerPlatform { get; set; }
    }
}
