//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Themes
    {
        public Themes()
        {
            this.OrderThemes = new HashSet<OrderThemes>();
            this.PerformerPlatform = new HashSet<PerformerPlatform>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<OrderThemes> OrderThemes { get; set; }
        public virtual ICollection<PerformerPlatform> PerformerPlatform { get; set; }
    }
}
