//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketThemes
    {
        public TicketThemes()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public long Id { get; set; }
        public string ThemeName { get; set; }
    
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
