//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AlertMessage = new HashSet<AlertMessage>();
            this.Ban = new HashSet<Ban>();
            this.Ban1 = new HashSet<Ban>();
            this.Ban2 = new HashSet<Ban>();
            this.BlackList = new HashSet<BlackList>();
            this.BlackList1 = new HashSet<BlackList>();
            this.Certificates = new HashSet<Certificates>();
            this.Cheaters = new HashSet<Cheaters>();
            this.Image = new HashSet<Image>();
            this.Messages = new HashSet<Messages>();
            this.Messages1 = new HashSet<Messages>();
            this.MoneyTransfers = new HashSet<MoneyTransfers>();
            this.News = new HashSet<News>();
            this.Order = new HashSet<Order>();
            this.OrderPerformed = new HashSet<OrderPerformed>();
            this.PerformerPlatform = new HashSet<PerformerPlatform>();
            this.Tickets = new HashSet<Tickets>();
            this.Tickets1 = new HashSet<Tickets>();
            this.Tickets2 = new HashSet<Tickets>();
            this.Transactions = new HashSet<Transactions>();
            this.Transactions1 = new HashSet<Transactions>();
            this.User1 = new HashSet<User>();
            this.UserMerchants = new HashSet<UserMerchants>();
            this.Video = new HashSet<Video>();
            this.Wallet = new HashSet<Wallet>();
            this.WhiteList = new HashSet<WhiteList>();
            this.WhiteList1 = new HashSet<WhiteList>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<long> RoleId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<long> TimeZoneId { get; set; }
        public Nullable<long> ReferrerId { get; set; }
        public string Status { get; set; }
        public string PasswordSalt { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public string LastLoginIp { get; set; }
        public bool IsActivated { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime LastLockedOutDate { get; set; }
        public string LastLockedOutReason { get; set; }
        public string NewPasswordKey { get; set; }
        public string NewEmail { get; set; }
        public string NewEmailKey { get; set; }
        public Nullable<System.DateTime> NewEmailRequested { get; set; }
        public Nullable<long> Rating { get; set; }
        public Nullable<long> Karma { get; set; }
        public Nullable<System.DateTime> LastOnlineDateTime { get; set; }
        public Nullable<System.DateTime> LastEmailSendDateTime { get; set; }
        public string AccountAttachedIP { get; set; }
        public Nullable<long> RegisteredRoleId { get; set; }
        public string VerificationKey { get; set; }
    
        public virtual ICollection<AlertMessage> AlertMessage { get; set; }
        public virtual ICollection<Ban> Ban { get; set; }
        public virtual ICollection<Ban> Ban1 { get; set; }
        public virtual ICollection<Ban> Ban2 { get; set; }
        public virtual ICollection<BlackList> BlackList { get; set; }
        public virtual ICollection<BlackList> BlackList1 { get; set; }
        public virtual ICollection<Certificates> Certificates { get; set; }
        public virtual ICollection<Cheaters> Cheaters { get; set; }
        public virtual ICollection<Image> Image { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Messages> Messages1 { get; set; }
        public virtual ICollection<MoneyTransfers> MoneyTransfers { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<OrderPerformed> OrderPerformed { get; set; }
        public virtual ICollection<PerformerPlatform> PerformerPlatform { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
        public virtual ICollection<Tickets> Tickets1 { get; set; }
        public virtual ICollection<Tickets> Tickets2 { get; set; }
        public virtual Timezone Timezone { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
        public virtual ICollection<Transactions> Transactions1 { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<UserMerchants> UserMerchants { get; set; }
        public virtual ICollection<Video> Video { get; set; }
        public virtual ICollection<Wallet> Wallet { get; set; }
        public virtual ICollection<WhiteList> WhiteList { get; set; }
        public virtual ICollection<WhiteList> WhiteList1 { get; set; }
    }
}
