//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodadModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.OrderContent = new HashSet<OrderContent>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public string VideoName { get; set; }
        public string VideoLink { get; set; }
        public long VideoSize { get; set; }
        public long VideoLength { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Extension { get; set; }
    
        public virtual ICollection<OrderContent> OrderContent { get; set; }
        public virtual User User { get; set; }
    }
}
